name: lyrics_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # Local Storage (switched to Hive for NoSQL, Mongo prep)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Data Models & Serialization
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  
  # Dependency Injection
  get_it: ^8.0.2
  injectable: ^2.5.0
  
  # Utilities
  dartz: ^0.10.1
  intl: ^0.20.2
  share_plus: ^10.1.2
  reorderables: ^0.6.0
  file_picker: ^8.1.2  # Added for import
  dio: ^5.6.0  # Added for future HTTP to Go/Mongo

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting & Code Generation
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2
  hive_generator: ^2.0.1  # Added for Hive
  
  # Testing
  mockito: ^5.4.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true