// Mocks generated by Mockito 5.4.5 from annotations
// in lyrics_app/test/features/lyrics/presentation/bloc/lyrics_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:lyrics_app/core/error/failures.dart' as _i6;
import 'package:lyrics_app/core/usecases/usecase.dart' as _i8;
import 'package:lyrics_app/features/lyrics/domain/entities/lyric.dart' as _i7;
import 'package:lyrics_app/features/lyrics/domain/repositories/lyrics_repository.dart'
    as _i2;
import 'package:lyrics_app/features/lyrics/domain/usecases/create_lyric.dart'
    as _i9;
import 'package:lyrics_app/features/lyrics/domain/usecases/get_all_lyrics.dart'
    as _i4;
import 'package:lyrics_app/features/lyrics/domain/usecases/search_lyrics.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLyricsRepository_0 extends _i1.SmartFake
    implements _i2.LyricsRepository {
  _FakeLyricsRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetAllLyrics].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllLyrics extends _i1.Mock implements _i4.GetAllLyrics {
  MockGetAllLyrics() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LyricsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeLyricsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.LyricsRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Lyric>>> call(
          _i8.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, List<_i7.Lyric>>>.value(
            _FakeEither_1<_i6.Failure, List<_i7.Lyric>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Lyric>>>);
}

/// A class which mocks [CreateLyric].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateLyric extends _i1.Mock implements _i9.CreateLyric {
  MockCreateLyric() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LyricsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeLyricsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.LyricsRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Lyric>> call(
          _i9.CreateLyricParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Lyric>>.value(
            _FakeEither_1<_i6.Failure, _i7.Lyric>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Lyric>>);
}

/// A class which mocks [SearchLyrics].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchLyrics extends _i1.Mock implements _i10.SearchLyrics {
  MockSearchLyrics() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LyricsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeLyricsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.LyricsRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Lyric>>> call(
          _i10.SearchLyricsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, List<_i7.Lyric>>>.value(
            _FakeEither_1<_i6.Failure, List<_i7.Lyric>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Lyric>>>);
}
